### ISSUE TITLE
Adjustments to level 1 layout

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#238]

**Comment by tommps** [comment]
For level one our team was planning on making some slight adjustments to make it a little less linear (plan to draft and implement it this week of the sprint) so you may need to wait until that is done before you set out the enemies and items (sorry for any inconvenience in having to wait). 

Also on that note did you want initial enemy/item settings for the level once we change it or did you want us to leave it blank for you to set it out completely yourself?

Additionally is there an excel sheet for level 1 that I would be able to have a copy of in order to make the changes (as there is for level two and three, cannot find it in the wiki where I found the other two)?

Thanks in advance
